### ISSUE TITLE
Response body validation

### ISSUE THREAD

**Issue by netiperher** [ecyrbe/zodios-express#100]
Hi,
Would it be possible to perform validation of the response object similar to how the request is validated by injecting an extra middleware? 

From what I understand only clients perform the response validation today, but with this feature problems could be detected earlier already in the server.

**Comment by ecyrbe** [comment]
Sorry for the late answer, yes this could be made possible as long as it's optional. 
I can add this feature after v11 release, or a pull request is welcomed if you need it sooner.

**Comment by blade2005** [comment]
I was actually just looking for this possibility. In the code I'm working on the User internally has `isAdmin` but the api response shouldn't have that. So just taking the schema and running a parse against it would be great!

**Comment by piedrahitapablo** [comment]
This can also be a great idea to ensure that the response does not include any secret or unwanted information, please give me any pointers on how this should be implemented and I'll try to do it since I think it will be a great feature
