### ISSUE TITLE
Allow handling validation errors

### ISSUE THREAD

**Issue by lnogol** [ecyrbe/zodios-express#140]
Zodios currently sends a response when validation fails:

```ts
return res.status(400).json({ ... });
```

This is fine by default, but it should also allow to handle the error manually in express error handler by calling `next(err)` instead.

Perhaps as a toggle passed to `.app()` and exporting `isZodiosValidationError(err)`

**Comment by ecyrbe** [comment]
@dwidge just implemented this. and is available in `v10.6.0`
