### ISSUE TITLE
Header and Body types are not present

### ISSUE THREAD

**Issue by Reptarsrage** [ecyrbe/zodios-express#181]
For example, given:

```ts
import { z } from 'zod';
import { makeApi } from '@zodios/core';
import { zodiosApp } from '@zodios/express';

const PostSchema = z.object({
  id: z.number(),
  name: z.string(),
});

const apiDefinition = makeApi([
  {
    method: 'post',
    path: '/api/create',
    alias: 'createPost',
    description: 'Create a post',
    response: PostSchema,
    parameters: [
      {
        name: 'name',
        description: 'Name of post',
        type: 'Body',
        schema: z.string(),
      },
    ],
  },
]);

const app = zodiosApp(apiDefinition);

app.post('/api/create', async (request, response) => {
  const { name } = request.body; // <- name has "any" type here

  const postResponse = await service.createPost(name);
  response.json(postResponse);
});

app.listen(3000);
```

### Expected:
name should have type "string"

### Actual:
name has type "any"

Same thing happens with `Headers` and `Body` type parameters. `Query` and `Path` work as expected.

**Comment by ecyrbe** [comment]
This is most likely due to:
- bad tsconfig
- forget to add the ts @types/... libs

Please share a full example repository or read the install docs carrefully.

**Comment by Reptarsrage** [comment]
Here's my `tsconfig.json`

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ES2019",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "lib": ["ES2019"],
    "outDir": "./lib",
    "alwaysStrict": true,
    "strict": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": true,
    "rootDir": "./src"
  }
}
```

**Comment by ecyrbe** [comment]
and your package.json ?

**Comment by ecyrbe** [comment]
Also you have an issue in your code, since body should be a string you can't get 'name' from a string, instead do : 
```ts
import { z } from 'zod';
import { makeApi } from '@zodios/core';
import { zodiosApp } from '@zodios/express';

const PostSchema = z.object({
  id: z.number(),
  name: z.string(),
});

const apiDefinition = makeApi([
  {
    method: 'post',
    path: '/api/create',
    alias: 'createPost',
    description: 'Create a post',
    response: PostSchema,
    parameters: [
      {
        name: 'name',
        description: 'Name of post',
        type: 'Body',
        schema: z.string(),
      },
    ],
  },
]);

const app = zodiosApp(apiDefinition);

app.post('/api/create', async (request, response) => {
  const name = request.body; // <- body is a string you can't destructure it

  const postResponse = await service.createPost(name); // <- don't forget to add try catch else errors will not be catched
  response.json(postResponse);
});

app.listen(3000);
```

**Comment by ecyrbe** [comment]
and here what your dependencies should at least have : 
```json
    "@types/express": "4.17.17",
    "@types/node": "18.15.11",
    "@zodios/core": "10.8.0",
    "axios": "1.3.4",
    "express": "4.18.2",
    "typescript": "5.0.3",
    "zod": "3.21.4"
```

**Comment by ecyrbe** [comment]
here is an example of correct setup working fine :  
https://codesandbox.io/s/typescript-playground-export-forked-b9ip50?file=/index.ts

**Comment by Reptarsrage** [comment]
OH MY GOD I just understood how this library is intended to work. 

I figured you would write something like...

```ts
const apiDefinition = makeApi([
  {
    method: 'post',
    path: '/api/create',
    alias: 'createPost',
    description: 'Create a post',
    response: PostSchema,
    parameters: [
      {
        name: 'name',
        description: 'Name of post',
        type: 'Body',
        schema: z.string(),
      },
      {
        name: 'definition',
        description: 'Definition of post',
        type: 'Body',
        schema: z.string(),
      },
      {
        name: 'author',
        description: 'Author of post',
        type: 'Body',
        schema: z.string(),
      },
    ],
  },
]);
```

...and the library would give me `request.body` as `{ name: '', definition: '', author: '' }`.

Now I understand that this library expects it to look like...

```ts
const apiDefinition = makeApi([
  {
    method: 'post',
    path: '/api/create',
    alias: 'createPost',
    description: 'Create a post',
    response: PostSchema,
    parameters: [
      {
        name: 'name',
        description: 'Name of post',
        type: 'Body',
        schema: z.object({
           name: z.string(),
           definition: z.string(),
           author: z.string(),
        }),
      },
    ],
  },
]);
```

...which totally makes sense but is a bit unintuative because of the array in the conifg. The library shouldn't allow users to define more than one body parameter, right? So why design it to use an array? Have you considered adding a new config property for defining the schema of the request body as an object allowing only a single definition?

**Comment by ecyrbe** [comment]
The array is mainly for allowing other parameters. And yes, there can be a runtime check to prevent you from loading many body definitions.

To get back to your issue. is it fixed with the exemples ?

can we close this issue ?

**Comment by ecyrbe** [comment]
more runtime checks have been added to api to detect duplicate body. available in `@zodios/core` `v10.8.1`

**Comment by Reptarsrage** [comment]
Sounds like you won't consider making this field an object and using the parameters array for other types of parameters (header,query,path). Shame. I think it would really help new users (like me) understand how to use the library before runtime errors start being thrown, or as in my case, no errors at all were thrown. Feel free to close this issue and thank you so much for the help!

**Comment by Reptarsrage** [comment]
Actually it's still very unclear what parameters are expected to be defined as a multitude of single schemas vs a single object schema. I know this is not true fro 'Body' type parameters. Those are expected to be defined only one. Is it also true for header parameters? What about query and path parameters?

**Comment by ecyrbe** [comment]
Only Body can't be duplicated schema.  
  
Indeed, body could be anything, an array, a string, a boolean, not just an object. 
So body can't be made to use distinct fields like you are asking for. it would break users code.
  
But other fields are named and for exemple, you need to add a field for each header, path or query parameter. so they are perfectly fine as arrays. 

Exeption is for body, like i explained.

**Comment by Reptarsrage** [comment]
I REALLY think you should consider refactoring your configuration to address this inconsistency, or at the very least add some additional documentation around this. It's a really cool library and I would love to see it continue to improve!

**Comment by ecyrbe** [comment]
Documentation will definitely be updated. Thank you for the feedback
