### ISSUE TITLE
This type error happens only with 10.6.1, 10.6.0 is fine

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios-express#193]
![image](https://user-images.githubusercontent.com/5043/233431501-0dcb6312-1847-4a57-8335-ea62e8c8c590.png)

**Comment by tribixbite** [comment]
fyi (dont feel it's worth opening a new issue, just wanted to share in case this helps anyone) - 
trying to run latest zodios (10.9) with nextjs v13.3 throws:
`SyntaxError: The requested module 'axios' does not provide an export named 'AxiosError'`
i was able to resolve it by reverting axios to 1.2.6
