### ISSUE TITLE
How to handle async route handlers?

### ISSUE THREAD

**Issue by yanfaliupst** [ecyrbe/zodios-express#204]
Firstly, thank you for this project, it's very useful. So I have a question about express 4 and it's inability to handle async routes correctly. Is there some example code with how to handle this use case correctly when using ZodiosRouter? I took a the look at the code and it doesn't appear to handle this use case.

e.g.
```typescript
router.get('/somepath', async () => {
  throw 'uh oh';
});
```

If you try this with express 4, your client will never get a response and eventually time out. Any suggestions on how to safely handle this use case beyond doing a simple try catch block? It would be nice to do this using some kind of higher order function, I was wondering if you could suggest something as my own typescript skills aren't as well developed.

```typescript
e.g.
router.get('/somepath', async (req, resp, next) => {
  try {
    throw new Error('uh oh');
  } catch (error: any) {
    Promise.reject(error);
    next(error);
  }
});
```

Thanks in advance.

[Article](https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016), better explaining the issue.

Updating comment to reflect actual tested reality.

**Comment by ecyrbe** [comment]
Hello,

Zodios server is just express with typesafety.
If you want async errors to be catched either :
- add try catch blocks
- add a monkey patch error like https://www.npmjs.com/package/express-async-errors
