### ISSUE TITLE
How we can get type autocompletion in route handler if we refactor it to different file (ex: controller)

### ISSUE THREAD

**Issue by rajesh-jangid-capsitech** [ecyrbe/zodios-express#208]
1. Created API definitions using API builder like the below file (product.apidefs.ts).
2. Able to get autocompletion in router's put API as I wrote the function in the route (product.route.ts).
3. But in POST API I refactored the handler to a different file product.controller.ts, Now what type do we need to use in the req parameter of the handler function? I checked the API documentation but was unable to figure it out. Is there any possibility of auto-type inference which we get in route handlers directly, otherwise I will need to manually export types of body and params for each route handler.
Are there any internal types that will be helpful in that scenario?

Please find the below attachment with all three files which I mentioned in the above points.
[code.zip](https://github.com/ecyrbe/zodios-express/files/11494343/code.zip)

**Comment by rajesh-jangid-capsitech** [comment]
Was able to implement it using the ZodiosRequestHandler type.

**Comment by robdefeo** [comment]
@rajesh-jangid-capsitech can you post an example of how you did this. I am also having the same issue, while I tried with `ZodiosRequestHandler` I haven't figured it out yet.
