### ISSUE TITLE
`FormData` requests are incorrectly validated before being processed by `multer`

### ISSUE THREAD

**Issue by vedxyz** [ecyrbe/zodios-express#220]
When using routes that receive a `FormData` request, the `defaultErrorHandler` thinks the fields in the form are all `undefined`. However, if validation is disabled, one can see within the request handler that the field is in fact populated and not `undefined`. So it appears the error handler is being run before `multer` can read the `FormData` and populate the `Request` object.

Here's a minimal reproduction branch/commit with new tests: d108b6296749bd55b7cf01963594e8170612934d
I can also make a PR with these tests, if it makes sense. I'm not sure there's a reason to merge them without a solution in sight though.

Note how disabling the validation like below makes the test pass (as it should):
https://github.com/vedxyz/zodios-express/blob/d108b6296749bd55b7cf01963594e8170612934d/src/zodios.spec.ts#L440-L441

---

As a sidenote, using `multer` with `zodios-express` is currently painful and feels hacky, I think it also deserves a spot on the roadmap for better/easier integration. Perhaps the ideal way to fix the issue above might even require tighter integration with `multer`?

**Comment by ecyrbe** [comment]
Thanks for the report,

I think you are right about integration.
It's a work i wanted to do and did not found time to do it.
So any help in the form of an RFC to propose an integration solution and a PR to follow is welcomed.

In the mean time a quick win solution would be to just disable validation if endpoint format is 'form-data'

Would this quick win solve your issue ?

**Comment by vedxyz** [comment]
Indeed, disabling validation has been my solution so far, and while it is an inconvenience, it's not a particularly big issue.

I can't work on a fleshed out RFC at the moment, but I did reach a working idea (with help from #81) to use utility functions to create type-compatible multer middlewares [like so](https://github.com/ecyrbe/zodios-express/blob/d108b6296749bd55b7cf01963594e8170612934d/src/multer.utils.ts#L25-L29).
I suspect you would eventually be able to formulate a much more reliable design for a multer integration than I currently can though.
