### ISSUE TITLE
Router route has incorrect types for NextJs

### ISSUE THREAD

**Issue by alex-way** [ecyrbe/zodios-express#266]
When using a Zodios Router in a NextJs project, the types inferred are using `express` Request/Response types rather than NextJs.

Would it be possible to have some kind've argument on the router to tell it to configure the NextJs types?

![image](https://github.com/ecyrbe/zodios-express/assets/29122169/749eb2d1-135c-4662-9273-7c6745629a5e)

**Comment by ecyrbe** [comment]
Hello, in fact they are really express ones.
nextjs is encapsulated in express and the instance are replaced by node ones by express.
not sure nextjs one are still there after that.
maybe if you explain your use case i can propose a workaround ?
