### ISSUE TITLE
Enforce non-error status codes

### ISSUE THREAD

**Issue by netiperher** [ecyrbe/zodios-express#99]
Hi,
Would it be possible to enforce the the status property in the express response handler (if specified), today it allows a small set of successful status codes (`ZodiosSucessCodes`) regardless of if this property is defined in the contract or not.

e.g. this example should result in compile time error
```
const userApi = makeApi([
  {
    method: "post",
    path: "/users",
    alias: "createUser",
    status: 201,
    response: z.object({
      id: z.number(),
      name: z.string().nullable(),
    }),
  },
]);

const app = zodiosApp(userApi);

app.post("/users", async (req, res) => {
  return res.status(200).json({
    id: 42,
    name: "example",
  });
});
```

**Comment by ecyrbe** [comment]
This is doable, but after v11 release. 
Help to add this kind of small feature is welcomed.
